# Generated by Django 5.0.3 on 2024-03-25 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_end_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='end_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuer', to=settings.AUTH_USER_MODEL),
        ),
    ]
