# Generated by Django 5.0.3 on 2024-04-01 13:00

import payments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_end_user_alter_payment_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(default=payments.utils.gen_external_id),
        ),
    ]
