# Generated by Django 5.0.3 on 2024-05-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_external_id'),
        ('payments', '0004_payment_name_payment_status'),
    ]

    operations = [
    ]
