# Generated by Django 5.0.3 on 2024-04-30 06:02

import payments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_name_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(default=payments.utils.gen_external_id),
        ),
    ]
