# Generated by Django 5.0.3 on 2024-05-17 08:00

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merge_20240503_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł')], decimal_places=2, max_digits=7, validators=[djmoney.models.validators.MinMoneyValidator({'EUR': 1, 'PLN': 5}), djmoney.models.validators.MaxMoneyValidator({'EUR': 20000, 'PLN': 99999})]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł')], default=None, editable=False, max_length=3),
        ),
    ]
