# Generated by Django 5.0.3 on 2024-05-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
