version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - /var/lib/postgresql/data

  django:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./:/usr/src/app

